[package]
name = "shaderjoy"
version = "0.1.0"
authors = ["Luis Wirth <lwirth2000@gmail.com>"]
edition = "2021"

[dependencies]
winit = "0.28.6"
wgpu = "0.16.1"

bytemuck = { version = "1.13.1", features = ["derive"] }
pollster = "0.3.0"
env_logger = "0.10.0"
